name: .NET Core

on: [push]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build TextDeserializer/TextDeserializer.sln --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release TextDeserializer/TextDeserializer.sln
    - uses: einaregilsson/build-number@v1
      with:
        token: ${{secrets.github_token}}
    - name: Publish
      run: dotnet nuget push "bin/Release/TextDeserializer.0.$BUILD_NUMBER.0-dev.nupkg"
