name: .NET Core

on: [push]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build TextDeserializer/TextDeserializer.sln --configuration Release
    - name: Publish with dotnet
      run: dotnet publish --configuration Release TextDeserializer/TextDeserializer.sln
    - name: Publish TextDeserializer artifacts to GitHub
      uses: actions/upload-artifact@v1
      with:
        name: TextDeserializer
        path: TextDeserializer/bin/Release/netcoreapp3.1/publish
